const os=require("os")
console.log("platform:",os.platform())
console.log("architecture:",os.arch())
console.log("free memory:",os.freemem())
console.log("host name:",os.hostname())
console.log("total memory:",os.totalmem())
console.log("home dir:",os.homedir())
console.log("type:",os.type())
console.log("release:",os.release())
console.log("up time:",os.uptime())
